development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  host: localhost
  pool: 5
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_USER_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  host: localhost
  pool: 5
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_USER_PASSWORD'] %>
