development:
  adapter: postgresql
  encoding: unicode
  database: the_project_dev
  host: localhost
  pool: 5
  username: maya
  password: bbjbjn

test:
  adapter: postgresql
  encoding: unicode
  database: the_project_test
  host: localhost
  pool: 5
  username: maya
  password: bbjbjn
